### ISSUE TITLE
Possible to do a brew bundle export?

### ISSUE THREAD

**Issue by ionlights** [lra/mackup#1508]
# Broadly, a feature request
So glad I found this, handles quite a bit of what I've done with shell scripting. Apologies on the long post, I figured it would be easier to outline everything as much as possible. 😅

## Inspiration / Background:
I've haphazardly automated some of my config backups and package installation, but `mackup` does a better job generalizing than I have, at least on the config side. 😀

**Does it make sense for `mackup` to potentially support acting as a [rudimetnary] package exporter/installer?**
- `brew` is trying to support Linux. I think strictly supporting `brew` might keep `mackup` from detrimentally expanding it's scope, while still maintaining a degree of platform agnosticism.
- `Brewfile`s are easily exported from `brew bundle`, but they need to be generated. It's easy enough to write-up a script to do the exports, but `mackup` doesn't support `Brewfile`s, period.

### Naïvely:
- Just add a `Brewfile` application that uses the "global" `~/.Brewfile` that `brew bundle` supports.
   This shouldn't modify the behavior of `mackup`, it just adds `Brewfile` support.

### More nicely (a personal favorite)
- Support generating a "custom" `Brewfile` (that is, it can be arbitrarily placed).
   This does like above, but I think would necessitate modifying `~/.mackup.cfg` to allow users to specify a particular location for this. Maybe something like...
   ```toml
   # ...
   
   # no attachment here, just based on the current directory structure
   [applications.Brewfile]
   # customization so that we can use a non-standard location
   path = "/path/to/Brewfile"
   # this could honestly just be a constant and we only allow for path modification
   file = "Brewfile"
   
   # ...
   ```
- Support an actual system installation.
   What I mean here is that `mackup` provides a new command `setup`, which differs from `mackup restore` only in that it prompts the user about performing an action like `brew bundle install --file=<file>`.
   Honestly, this could just be a question asked by `mackup restore`.
- Support `Brewfile` diff, of some sort (I need to look into this further).
   The main idea here is to check whether or not they've installed any packages since the last `Brewfile` was dumped and do a `brew bundle dump --file=` if they have. **Naïvely** we could just ask to overwrite the `Brewfile`, I'm not not sure of the impact on how quickly `mackup` might be able to run a diff (since `brew` can sometimes take a minute).

## Notes on specifying file locations:
- I don't think we really need to support specifying different filenames than `Brewfile` (though this could be a hangup for people trying to use `brew` on MacOS and Linux).
- I have a personal preference towards maintaining as much `XDG_CONFIG_HOME` compliance as possible, so a sensible default to me would be to place the Brewfile in `~/.config/brew/Brewfile`. (Opening another issue about globally preferring `$XDG_CONFIG_HOME` as a preference.)
- `brew` supports a global `~/.Brewfile` which could also be a default that's used.
- Then, of course, we could always let the user specify the file path in `~/.mackup.cfg`
